# Site settings
author: Tyler Croley
title: Journey Into the Realm of Software Development
header-img: img/home-bg.png
email: tjcroley@outlook.com
copyright_name: Tyler Croley
description: > # this means to ignore newlines until "baseurl:"
  One Small Step
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MisterAnthropy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
